version: "3.9"

services:
    postgresql:
        image: postgres:13.3-alpine
        environment:
            POSTGRES_DB: ${DOCKER_PG_DB}
            POSTGRES_USER: ${DOCKER_PG_USER}
            POSTGRES_PASSWORD: ${DOCKER_PG_PASSWORD}
        ports:
            -   5432:5432
        restart: always
    web:
        build: .
        environment:
            # NGINX-PROXY ENVIRONMENT VARIABLES: UPDATE ME
            - VIRTUAL_HOST=zerotohero.vietthai2512.digital
            - VIRTUAL_PORT=8080
            - LETSENCRYPT_HOST=zerotohero.vietthai2512.digital
            - LETSENCRYPT_EMAIL=vietthai2512@gmail.com
            # END NGINX-PROXY ENVIRONMENT VARIABLES
        depends_on:
            -   postgresql
        ports:
            -   8080:8080
        restart: always
